## Control Panel Module

## About state-card-tiles
## Original forum thread: https://community.home-assistant.io/t/custom-ui-button-panel/29513
## Official repo: https://github.com/c727/home-assistant-tiles

## Useful links
## Easy way to generate image for a tile: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
## Color blend: https://meyerweb.com/eric/tools/color-blend/

##################################################
## Customize
##################################################

homeassistant:
  customize:
    script.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 7
        row_height: 75px
        column_width: 62px
        gap: 15px
        color: '#262B38'
        color_on: 'var(--primary-color)'
        #color_on: '#262B38'
        color_off: '#616161'
        entities:
          # Line 1 - TV
          - entity: switch.tv
            caption: 
            icon: mdi:monitor
            column: 1
            row: 1
          - entity: script.tv_h1
            icon: mdi:android
            column: 2
            row: 1
          - entity: script.tv_antena
            icon: mdi:radio-tower
            column: 3
            row: 1
          - entity: script.tv_voldown
            icon: mdi:mdi:volume-medium
            column: 4
            row: 1            
          - entity: script.tv_volup
            icon: mdi:mdi:volume-high
            column: 5
            row: 1
          - entity: switch.tv_mute
            icon: mdi:volume-off
            column: 6
            row: 1
            
          # Line - AC
          - entity: switch.ac
            caption: 
            icon: mdi:fan
            column: 1
            row: 2
          - entity: script.ac_hot
            icon: mdi:white-balance-sunny
            color: '#D55C0E'
            column: 2
            row: 2
          - entity: script.ac_cold
            icon: mdi:mdi:snowflake
            color: '#4FA7FF'
            column: 3
            row: 2
            
          # Others
          - entity: script.mp_playpause
            icon: mdi:play-pause
            color: '#007009'
            column: 1
            row: 3
          - entity: script.sleep
            icon: mdi:hotel
            column: 2
            row: 3
          - entity: script.all_off
            icon: mdi:format-vertical-align-bottom
            color: '#FF4F52'
            column: 3
            row: 3
    
    script.remote_control_moods:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 5
        gap: 0px
        row_height: 88px
        column_width: 88px
        color: 'var(--paper-card-background-color)'
        entities:
          - entity: script.mp_radio
            image: /local/icons/kpop.png
            column: 1
            row: 1
          - entity: script.mp_podcast          
            image: /local/icons/podcast.png
            column: 2
            row: 1
          - entity: script.mp_barney
            image: /local/icons/barney.png
            column: 3
            row: 1
          - entity: script.mp_relax01
            image: /local/icons/rain.png
            column: 4
            row: 1
          - entity: script.mp_nature
            image: /local/icons/nature.png
            column: 5
            row: 1
            

##################################################
## Groups
##################################################

group:
  remote_control:
    name: Control Panel
    entities:
      - script.remote_control      
      - sensor.last_command
      
  remote_control_moods:
    name: Moods
    entities:
      - script.remote_control_moods
      - input_number.mp_volume


##################################################
## Scripts
##################################################
            
script:
  remote_control:
    sequence:
  
  remote_control_moods:
    sequence:
