homeassistant:
  customize:
    input_text.dummy_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        column_width: 75px
        row_height: 75px
        entities:
          - entity: script.play_radio
            image: /local/ok.png
            column: 2
            row: 5
            data: {value: ok}
          

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    
group:
  g1:
    name: Tiles showcase
    entities:
      - input_text.dummy_tiles
  

input_text:
  command:
    name: Button
  dummy_tiles:
    name: dummy
